[project]
channels = ["conda-forge"]
name = "icecream"
platforms = ["win-64"]
version = "2.1.5-dev"

[tasks]
tests = "python -m tox -q"

[dependencies]
python = ">=3.13.1,<3.14"
executing = ">=2.1.0,<3"
pygments = ">=2.19.1,<3"
asttokens = ">=3.0.0,<4"
colorama = ">=0.4.6,<0.5"
tox = ">=4.23.2,<5"
sympy = ">=1.13.3,<2"
icecream = ">=2.1.4,<3"
ipython = ">=8.31.0,<9"
